const readLine = require ('readline-sync');
readLine.question ("Enter Adjective:");
console.log ("MacDonald had a");
readLine.question ("Enter Noun:");
console.log (" E-I-E-I-O and on that");
readLine.question ("Enter Noun:");
console.log (" he had an");
readLine.question ("Enter Animal:");
console.log (" E-I-E-I-O with a");
readLine.question ("Enter Noise:");
readLine.question ("Enter Noise:");
console.log (" here and a");
readLine.question ("Enter Noise:");
readLine.question ("Enter Noise:");
console.log ("there, here a");
readLine.question ("Enter Noise:");
console.log ("there a");
readLine.question ("Enter Noise:");
console.log (" everywhere a");
readLine.question ("Enter Noise:");
readLine.question ("Enter Noise:");
readLine.question ("Enter Adjective:");
console.log ("MacDonald had a");
readLine.question ("Enter Noun:");
console.log (" E-I-E-I-O.");
readLine.question ("Enter Adjective:");
console.log (" MacDonald had a ");
readLine.question ("Enter Noun:");
console.log ("E-I-E-I-O and on that ");
readLine.question ("Enter Noun:");
console.log ("he had some  ");
readLine.question ("Enter Animal:");
console.log ("E-I-E-I-O! With a");
readLine.question ("Enter Noise:");
readLine.question ("Enter Noise:");
console.log (" here and a");
readLine.question ("Enter Noise:");
readLine.question ("Enter Noise:");
console.log ("there, here a");
readLine.question ("Enter Noise:");
console.log ("there a");
readLine.question ("Enter Noise:");
console.log (" everywhere a ");
readLine.question ("Enter Noise:");
readLine.question ("Enter Noise:");
readLine.question ("Enter Adjective:");
console.log ("MacDonald had a ");
readLine.question ("Enter Noun:");
console.log (" E-I-E-I-O.");